"$schema" = 'https://starship.rs/config-schema.json'

# Updated format using the "Noir" monochrome gradient
format = """
[](noir_black)\
$os\
$username\
[](bg:noir_charcoal fg:noir_black)\
$directory\
[](bg:noir_steel fg:noir_charcoal)\
$git_branch\
$git_status\
[](fg:noir_steel bg:noir_silver)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:noir_silver bg:noir_white)\
$conda\
[](fg:noir_white bg:noir_pure_white)\
$time\
[ ](fg:noir_pure_white)\
$cmd_duration\
$line_break\
$character"""

palette = 'noir'

#[os]
#disabled = false
#style = "bg:noir_black fg:noir_pure_white"

[username]
show_always = true
style_user = "bg:noir_black fg:noir_pure_white"
style_root = "bg:noir_black fg:noir_pure_white"
format = '[ $user]($style)'

[directory]
style = "bg:noir_charcoal fg:noir_pure_white"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:noir_steel"
format = '[[ $symbol $branch ](fg:noir_black bg:noir_steel)]($style)'

[git_status]
style = "bg:noir_steel"
format = '[[($all_status$ahead_behind )](fg:noir_black bg:noir_steel)]($style)'

# Languages (Mapped to noir_silver for contrast)
[nodejs]
symbol = ""
style = "bg:noir_silver"
format = '[[ $symbol( $version) ](fg:noir_black bg:noir_silver)]($style)'

[rust]
symbol = ""
style = "bg:noir_silver"
format = '[[ $symbol( $version) ](fg:noir_black bg:noir_silver)]($style)'

[python]
symbol = ""
style = "bg:noir_silver"
format = '[[ $symbol( $version)(\(#$virtualenv\)) ](fg:noir_black bg:noir_silver)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:noir_pure_white"
format = '[[  $time ](fg:noir_black bg:noir_pure_white)]($style)'

[character]
disabled = false
# Success is pure white, Error is a dark gray to keep it "noir"
success_symbol = '[❯](bold noir_pure_white)'
error_symbol = '[❯](bold noir_charcoal)'

# --- Noir Palette Definitions ---
[palettes.noir]
noir_black      = "#131313"
noir_charcoal   = "#343434"
noir_steel      = "#5d5d5e"
noir_silver     = "#8c8c8d"
noir_white      = "#c9c9c9"
noir_pure_white = "#ffffff"
